Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/02/2023
Var
// Seção de Declarações das variáveis 
j: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
j<-1
 repita
 escreval (j)
 j <-j+1
    se j=5 entao
    interrompa
    fimse
 ate j>10
 //detalhe, quando j fica maior que 10 (no caso 11) ele instantaneamente para, pois passou de 10 :)

Fimalgoritmo



